version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "inspection-service-db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"