name: Java CI with Maven

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Setup Postgres database
        uses: Daniel-Marynicz/postgresql-action@master
        with:
          postgres_image_tag: 16.0
          app_user: admin
          app_user_password: admin
          app_db: inspection-service-sb

      - name: Maven Package
        run: mvn -B clean package -DskipTests

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install CodeClimate CLI
        run: |
          curl -L https://github.com/codeclimate/codeclimate/archive/master.tar.gz | tar xvz
          mv codeclimate-* codeclimate
          chmod +x codeclimate
          sudo mv codeclimate /usr/local/bin/

      - name: Run CodeClimate Analysis
        run: |
          codeclimate analyze --dev
